async function getData() {
  //const { GoogleSpreadsheet } = require("google-spreadsheet");
  //   const doc = new GoogleSpreadsheet(
  //     "1dhGS_fETqxRCv5j8JGSpflEIuR_KYWmQp0pWtHoZLhM"
  //   );
  //   await doc.useServiceAccountAuth({
  //     // env var values are copied from service account credentials generated by google
  //     // see "Authentication" section in docs for more info
  //     client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  //     private_key: process.env.GOOGLE_PRIVATE_KEY,
  //   });
  //   await doc.loadInfo(); // loads document properties and worksheets
  //   console.log(doc.title);
  //   await doc.updateProperties({ title: "renamed doc" });
  //   const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
  //   console.log(sheet.title);
  //   console.log(sheet.rowCount);
  //   // adding / removing sheets
  //   const newSheet = await doc.addSheet({ title: "hot new sheet!" });
  //   await newSheet.delete();
}

export default getData;
